module.exports = [
  {
    "publicId": "card-tur-jardim",
    "pointId": "tur-jardim",
    "category": "turistico",
    "hasWifi": true,
    "name": "Praça Lourival Monte",
    "subtitle": "O Cartão-Postal de Amargosa",
    "description": "A Praça Lourival Monte, conhecida como \"Jardim\", é um dos espaços mais simbólicos de Amargosa O local reúne paisagismo marcante, vida urbana e a presença da Catedral de Nossa Senhora do Bom Conselho",
    "imageUrl": "public/images/hero-amargosa.jpeg",
    "imageAlt": "Praça Lourival Monte",
    "addressLine": "",
    "scheduleLine": "",
    "instagramUrl": "",
    "whatsappUrl": "",
    "email": "",
    "phone": "",
    "displayOrder": 1,
    "isActive": true,
    "latitude": -13.0316825,
    "longitude": -39.6035944,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=-13.0316825,-39.6035944",
    "markerIcon": "attraction"
  },
  {
    "publicId": "card-tur-bosque",
    "pointId": "tur-bosque",
    "category": "turistico",
    "hasWifi": true,
    "name": "Praça do Bosque",
    "subtitle": "Espaço de convivência e eventos",
    "description": "A Praça do Bosque é um espaço amplo e acolhedor para encontros, passeios em família e atividades culturais Sua estrutura recebe eventos e oferece uma área agradável para lazer e convivência",
    "imageUrl": "public/images/praca-do-bosque-antiga-estacao.jpg",
    "imageAlt": "Praça do Bosque",
    "addressLine": "",
    "scheduleLine": "",
    "instagramUrl": "",
    "whatsappUrl": "",
    "email": "",
    "phone": "",
    "displayOrder": 2,
    "isActive": true,
    "latitude": -13.0320631,
    "longitude": -39.6001171,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=-13.0320631,-39.6001171",
    "markerIcon": "attraction"
  },
  {
    "publicId": "card-tur-catedral",
    "pointId": "tur-catedral",
    "category": "turistico",
    "name": "Catedral de Nossa Senhora do Bom Conselho",
    "subtitle": "Patrimônio Histórico e Arquitetônico",
    "description": "Localizada na Praça Lourival Monte, a Catedral é um importante patrimônio histórico de Amargosa Sua arquitetura barroca preserva memórias religiosas, artísticas e culturais da cidade",
    "imageUrl": "public/images/catedral-de-amargosa.webp",
    "imageAlt": "Catedral de Nossa Senhora do Bom Conselho",
    "addressLine": "",
    "scheduleLine": "",
    "instagramUrl": "",
    "whatsappUrl": "",
    "email": "",
    "phone": "",
    "displayOrder": 3,
    "isActive": true,
    "latitude": -13.03142,
    "longitude": -39.60336,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=-13.03142,-39.60336",
    "markerIcon": "heritage"
  },
  {
    "publicId": "card-tur-minguara",
    "pointId": "tur-minguara",
    "category": "turistico",
    "hasWifi": true,
    "name": "Praça da Minguara",
    "subtitle": "Permanência e encontro no centro urbano",
    "description": "A Praça da Minguara revela o cotidiano de Amargosa com movimento tranquilo, encontros ao ar livre e permanência de moradores em diferentes horários do dia",
    "imageUrl": "public/images/praca-iraci-silva-praca-do-cristo.jpg",
    "imageAlt": "Praça da Minguara",
    "addressLine": "",
    "scheduleLine": "",
    "instagramUrl": "",
    "whatsappUrl": "",
    "email": "",
    "phone": "",
    "displayOrder": 4,
    "isActive": true,
    "latitude": -13.018943,
    "longitude": -39.602437,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=-13.018943,-39.602437",
    "markerIcon": "attraction"
  },
  {
    "publicId": "card-tur-santa-rita",
    "pointId": "tur-santa-rita",
    "category": "turistico",
    "hasWifi": true,
    "name": "Praça da Santa Rita",
    "subtitle": "Memória religiosa e identidade de bairro",
    "description": "Na região de Santa Rita, a praça compõe um cenário de forte identidade comunitária, com presença marcante na vida do bairro e ligação com encontros locais",
    "imageUrl": "public/images/catedral-de-amargosa.webp",
    "imageAlt": "Praça da Santa Rita",
    "addressLine": "",
    "scheduleLine": "",
    "instagramUrl": "",
    "whatsappUrl": "",
    "email": "",
    "phone": "",
    "displayOrder": 5,
    "isActive": true,
    "latitude": -13.0232761,
    "longitude": -39.6028166,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Pra%C3%A7a%20Constantino%20Sampaio,%20Santa%20Rita,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "attraction"
  },
  {
    "publicId": "card-tur-joao-angelo",
    "pointId": "tur-joao-angelo",
    "category": "turistico",
    "hasWifi": true,
    "name": "Praça João Ângelo Pereira",
    "subtitle": "Circulação e vida cotidiana no centro",
    "description": "A Praça João Ângelo Pereira integra a paisagem urbana do centro e funciona como ponto de passagem e permanência, conectando comércio, serviços e o ritmo diário da cidade",
    "imageUrl": "public/images/hero-calendario-praca-lourival-monte.jpg",
    "imageAlt": "Praça João Ângelo Pereira",
    "addressLine": "",
    "scheduleLine": "",
    "instagramUrl": "",
    "whatsappUrl": "",
    "email": "",
    "phone": "",
    "displayOrder": 6,
    "isActive": true,
    "latitude": -13.02608,
    "longitude": -39.605009,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=-13.026080,-39.605009",
    "markerIcon": "attraction"
  },
  {
    "publicId": "card-tur-duque-caxias",
    "pointId": "tur-duque-caxias",
    "category": "turistico",
    "hasWifi": true,
    "name": "Praça Duque de Caxias",
    "subtitle": "Entorno comercial e experiência do centro",
    "description": "A Praça Duque de Caxias se destaca pela localização estratégica em uma área de serviços e comércio, compondo a experiência de quem percorre o centro de Amargosa",
    "imageUrl": "public/images/hero-amargosa.jpeg",
    "imageAlt": "Praça Duque de Caxias",
    "addressLine": "",
    "scheduleLine": "",
    "instagramUrl": "",
    "whatsappUrl": "",
    "email": "",
    "phone": "",
    "displayOrder": 7,
    "isActive": true,
    "latitude": -13.029283,
    "longitude": -39.6048,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=-13.029283,-39.604800",
    "markerIcon": "attraction"
  },
  {
    "publicId": "card-tur-cristo",
    "pointId": "tur-cristo",
    "category": "turistico",
    "hasWifi": true,
    "name": "Praça do Cristo",
    "subtitle": "Vista urbana e passeio ao ar livre",
    "description": "A Praça do Cristo oferece um ponto conhecido da cidade para contemplação, caminhada e registro de visita, reunindo paisagem urbana e atmosfera tranquila em um dos espaços mais lembrados de Amargosa",
    "imageUrl": "public/images/praca-iraci-silva-praca-do-cristo.jpg",
    "imageAlt": "Praça do Cristo em Amargosa",
    "addressLine": "",
    "scheduleLine": "",
    "instagramUrl": "",
    "whatsappUrl": "",
    "email": "",
    "phone": "",
    "displayOrder": 8,
    "isActive": true,
    "latitude": -13.02974,
    "longitude": -39.602443,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=-13.029740,-39.602443",
    "markerIcon": "attraction"
  },
  {
    "publicId": "card-tur-barreiros",
    "pointId": "tur-barreiros",
    "category": "turistico",
    "hasWifi": true,
    "name": "Pracinha dos Barreiros",
    "subtitle": "Encontro comunitário e lazer de bairro",
    "description": "A Pracinha dos Barreiros é um espaço de lazer cotidiano que reúne moradores em encontros, descanso e atividades ao ar livre, reforçando a identidade afetiva das praças de Amargosa",
    "imageUrl": "public/images/hero-calendario-praca-lourival-monte.jpg",
    "imageAlt": "Pracinha dos Barreiros",
    "addressLine": "",
    "scheduleLine": "",
    "instagramUrl": "",
    "whatsappUrl": "",
    "email": "",
    "phone": "",
    "displayOrder": 9,
    "isActive": true,
    "latitude": -13.0116885,
    "longitude": -39.6211379,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=-13.0116885,-39.6211379",
    "markerIcon": "attraction"
  },
  {
    "publicId": "card-gas-casa-da-feijoada",
    "pointId": "gas-casa-da-feijoada",
    "category": "gastronomia",
    "name": "Casa da Feijoada",
    "subtitle": "Aqui você encontra a melhor feijoada de Amargosa",
    "description": "Referência para almoço no centro da cidade, com serviço diário e identidade gastronômica bem conhecida entre moradores e visitantes",
    "imageUrl": "public/images/gastronomia/casa-da-feijoada.png",
    "imageAlt": "Casa da Feijoada",
    "addressLine": "Rua Conselheiro Dantas, 15, Centro",
    "scheduleLine": "Todos os dias, das 11h às 15h",
    "instagramUrl": "https://www.instagram.com/casadafeijoada_/",
    "whatsappUrl": "https://wa.me/5575988251394",
    "email": "",
    "phone": "",
    "displayOrder": 10,
    "isActive": true,
    "latitude": -13.0300058,
    "longitude": -39.5980395,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Casa%20da%20Feijoada,%20Rua%20Conselheiro%20Dantas,%2015,%20Centro,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "gastronomy"
  },
  {
    "publicId": "card-gas-chef-restaurante",
    "pointId": "gas-chef-restaurante",
    "category": "gastronomia",
    "name": "Chef Restaurante e Pizzaria",
    "subtitle": "A sua pizzaria no Valle Shopping",
    "description": "Opção para refeições e pizzas no Valle Shopping, com atendimento diário e foco em consumo local e delivery",
    "imageUrl": "public/images/gastronomia/chef-restaurante-e-pizzaria.png",
    "imageAlt": "Chef Restaurante e Pizzaria",
    "addressLine": "Valle Shopping, Avenida Doutor Luis Sande de Oliveira, 196",
    "scheduleLine": "Todos os dias, das 16h às 22h",
    "instagramUrl": "https://www.instagram.com/chefpizzaria_/",
    "whatsappUrl": "https://wa.me/5575999130774",
    "email": "",
    "phone": "",
    "displayOrder": 11,
    "isActive": true,
    "latitude": -13.0238365,
    "longitude": -39.605897,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Chef%20Restaurante%20e%20Pizzaria,%20Valle%20Shopping,%20Avenida%20Doutor%20Luis%20Sande%20de%20Oliveira,%20196,%20Centro,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "gastronomy"
  },
  {
    "publicId": "card-gas-cantinho-da-evely",
    "pointId": "gas-cantinho-da-evely",
    "category": "gastronomia",
    "name": "Cantinho da Evely",
    "subtitle": "Refeições no Valle Shopping",
    "description": "Espaço gastronômico com atendimento ao longo da semana e presença ativa nas redes para pedidos e novidades",
    "imageUrl": "public/images/gastronomia/cantinho-da-evely.jpg",
    "imageAlt": "Cantinho da Evely",
    "addressLine": "Valle Shopping, Avenida Doutor Luis Sande de Oliveira, 196",
    "scheduleLine": "Segunda a partir das 15h; terça a sábado a partir das 11h30; domingo a partir das 12h30",
    "instagramUrl": "https://www.instagram.com/cantinho_evely/",
    "whatsappUrl": "https://wa.me/5575988182644",
    "email": "",
    "phone": "",
    "displayOrder": 12,
    "isActive": true,
    "latitude": -13.0235967,
    "longitude": -39.6065712,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Cantinho%20da%20Evely,%20Valle%20Shopping,%20Avenida%20Doutor%20Luis%20Sande%20de%20Oliveira,%20196,%20Centro,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "gastronomy"
  },
  {
    "publicId": "card-gas-3-marias",
    "pointId": "gas-3-marias",
    "category": "gastronomia",
    "name": "3 Marias",
    "subtitle": "Café da manhã na Praça dos Correios",
    "description": "Ponto indicado para café da manhã e refeições leves, em local central e de fácil acesso para quem circula pela cidade",
    "imageUrl": "public/images/gastronomia/3-marias.jpg",
    "imageAlt": "3 Marias",
    "addressLine": "Praça dos Correios",
    "scheduleLine": "Todos os dias, das 9h às 19h",
    "instagramUrl": "https://www.instagram.com/3mariasamargosa/",
    "whatsappUrl": "https://wa.me/5575992287847",
    "email": "",
    "phone": "",
    "displayOrder": 13,
    "isActive": true,
    "latitude": -13.02921,
    "longitude": -39.6047845,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=3%20Marias,%20Praca%20dos%20Correios,%20Centro,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "gastronomy"
  },
  {
    "publicId": "card-gas-boteco-boliche",
    "pointId": "gas-boteco-boliche",
    "category": "gastronomia",
    "name": "Boteco Boliche",
    "subtitle": "Parada descontraída no Valle Shopping",
    "description": "Espaço para encontro informal e consumo rápido, integrado ao fluxo comercial do Valle Shopping",
    "imageUrl": "public/images/gastronomia/boteco-boliche.webp",
    "imageAlt": "Boteco Boliche",
    "addressLine": "Valle Shopping, Avenida Doutor Luis Sande de Oliveira, 196",
    "scheduleLine": "Todos os dias, a partir das 9h",
    "instagramUrl": "https://www.instagram.com/botecodoboliche/",
    "whatsappUrl": "https://wa.me/5575998723955",
    "email": "",
    "phone": "",
    "displayOrder": 14,
    "isActive": true,
    "latitude": -13.0238365,
    "longitude": -39.605897,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Boteco%20Boliche,%20Valle%20Shopping,%20Avenida%20Doutor%20Luis%20Sande%20de%20Oliveira,%20196,%20Centro,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "gastronomy"
  },
  {
    "publicId": "card-gas-villa-galicia",
    "pointId": "gas-villa-galicia",
    "category": "gastronomia",
    "name": "Villa Galícia Horto Restaurante",
    "subtitle": "Almoço e experiência gastronômica",
    "description": "Restaurante indicado para refeições com atmosfera mais reservada, com funcionamento regular durante o dia e atendimento noturno por reserva",
    "imageUrl": "public/images/gastronomia/villa-galicia-horto.webp",
    "imageAlt": "Villa Galicia Horto Restaurante",
    "addressLine": "Av Lomanto Júnior, nº 35",
    "scheduleLine": "Quarta a domingo, das 11h às 17h; à noite apenas com reserva",
    "instagramUrl": "https://www.instagram.com/hortovillagalicia/",
    "whatsappUrl": "https://wa.me/5575988363209",
    "email": "",
    "phone": "",
    "displayOrder": 15,
    "isActive": true,
    "latitude": -13.0359043,
    "longitude": -39.6046664,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Villa%20Galicia%20Horto%20Restaurante,%20Avenida%20Lomanto%20Junior,%2035,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "gastronomy"
  },
  {
    "publicId": "card-gas-bella-roma",
    "pointId": "gas-bella-roma",
    "category": "gastronomia",
    "name": "Restaurante Bella Roma",
    "subtitle": "Próximo ao Largo Maracanã",
    "description": "Restaurante em uma área movimentada da cidade, com abertura regular para almoço e reuniões em família",
    "imageUrl": "public/images/gastronomia/bella-roma.webp",
    "imageAlt": "Restaurante Bella Roma",
    "addressLine": "Rio Branco, ao lado do Largo Maracanã",
    "scheduleLine": "Terça a domingo, a partir das 11h",
    "instagramUrl": "https://www.instagram.com/restaurantebellaroma/",
    "whatsappUrl": "https://wa.me/5575999022406",
    "email": "",
    "phone": "",
    "displayOrder": 16,
    "isActive": true,
    "latitude": -13.0300058,
    "longitude": -39.5980395,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Restaurante%20Bella%20Roma,%20Largo%20Maracana,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "gastronomy"
  },
  {
    "publicId": "card-gas-volupe",
    "pointId": "gas-volupe",
    "category": "gastronomia",
    "name": "Volupe Gastro Bar",
    "subtitle": "Noite e encontros no centro",
    "description": "Espaço gastronômico voltado para a vida noturna, com funcionamento estendido e ambiente de encontros no centro de Amargosa",
    "imageUrl": "public/images/gastronomia/volupe-gastro-bar.webp",
    "imageAlt": "Volupe Gastro Bar",
    "addressLine": "R da Lapinha, 209, Centro",
    "scheduleLine": "Todos os dias, das 18h à 0h; sábados até 2h",
    "instagramUrl": "https://www.instagram.com/volupegastrobar/",
    "whatsappUrl": "https://wa.me/5575991982702",
    "email": "",
    "phone": "",
    "displayOrder": 17,
    "isActive": true,
    "latitude": -13.025113,
    "longitude": -39.606495,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Volupe%20Gastro%20Bar,%20Rua%20da%20Lapinha,%20209,%20Centro,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "gastronomy"
  },
  {
    "publicId": "card-gas-saori",
    "pointId": "gas-saori",
    "category": "gastronomia",
    "name": "Saori Sushi",
    "subtitle": "Culinária japonesa no Amarcenter",
    "description": "Opção para quem busca sushi e pratos orientais, com atendimento noturno em uma área de fácil acesso",
    "imageUrl": "public/images/gastronomia/saori-sushi.webp",
    "imageAlt": "Saori Sushi",
    "addressLine": "Travessa Benito Almeida, Amarcenter",
    "scheduleLine": "Quinta a domingo, das 18h às 22h",
    "instagramUrl": "https://www.instagram.com/saori_sushihouse/",
    "whatsappUrl": "https://wa.me/5575988275216",
    "email": "",
    "phone": "",
    "displayOrder": 18,
    "isActive": true,
    "latitude": -13.0292654,
    "longitude": -39.605642,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Saori%20Sushi,%20Travessa%20Benedito%20Almeida,%20Amarcenter,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "gastronomy"
  },
  {
    "publicId": "card-gas-americano",
    "pointId": "gas-americano",
    "category": "gastronomia",
    "name": "Americano Bar e Lanchonete",
    "subtitle": "Parada clássica na Av Lomanto Júnior",
    "description": "Espaço para lanches e encontros informais em um dos corredores urbanos mais conhecidos da cidade",
    "imageUrl": "public/images/gastronomia/americano-bar-e-lanchonete.jpg",
    "imageAlt": "Americano Bar e Lanchonete",
    "addressLine": "Avenida Lomanto Júnior, 117, Centro",
    "scheduleLine": "Todos os dias, a partir das 8h",
    "instagramUrl": "",
    "whatsappUrl": "https://wa.me/5575988035650",
    "email": "",
    "phone": "",
    "displayOrder": 19,
    "isActive": true,
    "latitude": -13.0319602,
    "longitude": -39.604313,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Americano%20Bar%20e%20Lanchonete,%20Avenida%20Lomanto%20Junior,%20117,%20Centro,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "gastronomy"
  },
  {
    "publicId": "card-gas-pug-efemero",
    "pointId": "gas-pug-efemero",
    "category": "gastronomia",
    "name": "Pub e Bar Efêmero",
    "subtitle": "Bar próximo ao Bosque",
    "description": "Opção para encontros noturnos em uma região já conhecida pelo fluxo de bares e restaurantes na cidade",
    "imageUrl": "public/images/gastronomia/pub-e-bar-efemero.png",
    "imageAlt": "Pub e Bar Efêmero",
    "addressLine": "R Carlos Gomes, próximo ao Bosque",
    "scheduleLine": "Quinta a domingo, das 19h às 23h",
    "instagramUrl": "https://instagram.com/efemero_craft_beer/",
    "whatsappUrl": "https://wa.me/5575988665360",
    "email": "",
    "phone": "",
    "displayOrder": 20,
    "isActive": true,
    "latitude": -13.0312651,
    "longitude": -39.6001785,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Pub%20e%20Bar%20Efemero,%20Rua%20Carlos%20Gomes,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "gastronomy"
  },
  {
    "publicId": "card-gas-restaurante-sias",
    "pointId": "gas-restaurante-sias",
    "category": "gastronomia",
    "name": "Restaurante e Pizzaria do Sias",
    "subtitle": "Em frente à Praça Iraci Silva",
    "description": "Restaurante de funcionamento diário em um ponto urbano de fácil localização, próximo a uma das praças mais conhecidas da cidade",
    "imageUrl": "public/images/gastronomia/restaurante-do-sias.webp",
    "imageAlt": "Restaurante e Pizzaria do Sias",
    "addressLine": "Travessa Almeida Sampaio, 250",
    "scheduleLine": "Todos os dias, das 11h às 22h",
    "instagramUrl": "https://www.instagram.com/restauranteepizzariadosias_/",
    "whatsappUrl": "https://wa.me/5575988610863",
    "email": "",
    "phone": "",
    "displayOrder": 21,
    "isActive": true,
    "latitude": -13.0292726,
    "longitude": -39.6023098,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Restaurante%20e%20Pizzaria%20do%20Sias,%20Travessa%20Almeida%20Sampaio,%20250,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "gastronomy"
  },
  {
    "publicId": "card-hotel-calisto",
    "pointId": "hotel-calisto",
    "category": "hotel",
    "name": "Hotel e Pousada Calisto",
    "subtitle": "Hospedagem com café da manhã",
    "description": "Opção de hospedagem em área urbana de Amargosa, com serviço de café da manhã e localização de fácil acesso",
    "imageUrl": "public/images/pousadas/calisto.webp",
    "imageAlt": "Pousada Calisto",
    "addressLine": "Aberto",
    "scheduleLine": "",
    "instagramUrl": "https://www.instagram.com/hotelcalisto/",
    "whatsappUrl": "https://wa.me/5575999152095",
    "email": "nkcarlisto@gmail.com",
    "phone": "Av Abelardo Veloso, 258",
    "displayOrder": 22,
    "isActive": true,
    "latitude": -13.0299687,
    "longitude": -39.5987767,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Pousada%20Calisto,%20Avenida%20Abelardo%20Veloso,%20258,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "lodging"
  },
  {
    "publicId": "card-hotel-colibri",
    "pointId": "hotel-colibri",
    "category": "hotel",
    "name": "Hotel Fazenda Colibri",
    "subtitle": "Estadia na rota Amargosa-Mutuípe",
    "description": "Opção de hospedagem com perfil de hotel fazenda para quem busca estadia em ambiente mais tranquilo e com acesso pela rodovia",
    "imageUrl": "public/images/pousadas/colibri.webp",
    "imageAlt": "Hotel Fazenda Colibri",
    "addressLine": "Aberto todos os dias",
    "scheduleLine": "",
    "instagramUrl": "https://www.instagram.com/hotelfazendacolibri/",
    "whatsappUrl": "",
    "email": "hotelfazendacolibri@hotmail.com",
    "phone": "+557536341009",
    "displayOrder": 23,
    "isActive": true,
    "latitude": -13.0421524,
    "longitude": -39.5816165,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Hotel%20Fazenda%20Colibri,%20Rodovia%20Amargosa-Mutuipe,%20km%202,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "lodging"
  },
  {
    "publicId": "card-hotel-vale-aguas",
    "pointId": "hotel-vale-aguas",
    "category": "hotel",
    "name": "Hotel Fazenda Vale das Águas",
    "subtitle": "Hospedagem rural na rodovia",
    "description": "Estadia com perfil de hotel fazenda na rodovia Amargosa-Mutuipe, indicada para visitantes que buscam uma experiência de hospedagem mais reservada",
    "imageUrl": "public/images/pousadas/vale-das-aguas.webp",
    "imageAlt": "Hotel Fazenda Vale das Águas",
    "addressLine": "Aberto todos os dias",
    "scheduleLine": "",
    "instagramUrl": "https://www.instagram.com/hfvaledasaguas/",
    "whatsappUrl": "https://wa.me/5575988971241",
    "email": "nubiamoares123@gmail.com",
    "phone": "nubiamoares123@gmailcom",
    "displayOrder": 24,
    "isActive": true,
    "latitude": -13.0687402,
    "longitude": -39.5669952,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Hotel%20Fazenda%20Vale%20das%20Aguas,%20BA-540,%20km%205,%20Fazenda%20Reunidas%20Ribeirao%20do%20Cupido,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "lodging"
  },
  {
    "publicId": "card-hotel-katiara",
    "pointId": "hotel-katiara",
    "category": "hotel",
    "name": "Pousada Katiara",
    "subtitle": "Hospedagem urbana em Amargosa",
    "description": "Opção de pousada cadastrada no guia local, com contato direto por e-mail e telefone",
    "imageUrl": "public/images/pousadas/katiara.webp",
    "imageAlt": "Pousada Katiara",
    "addressLine": "Avenida Abelardo Veloso, 470, Centro",
    "scheduleLine": "",
    "instagramUrl": "https://www.instagram.com/pousadakatyara/",
    "whatsappUrl": "",
    "email": "pousadakatiara@yahoo.com.br",
    "phone": "+557536341075",
    "displayOrder": 25,
    "isActive": true,
    "latitude": -13.0302393,
    "longitude": -39.5941363,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Pousada%20Katiara,%20Avenida%20Abelardo%20Veloso,%20470,%20Centro,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "lodging"
  },
  {
    "publicId": "card-hotel-girassol",
    "pointId": "hotel-girassol",
    "category": "hotel",
    "name": "Pousada Girassol",
    "subtitle": "Contato direto para hospedagem",
    "description": "Meio de hospedagem com atendimento por e-mail e telefone móvel para reservas e informações",
    "imageUrl": "public/images/pousadas/girassol.webp",
    "imageAlt": "Pousada Girassol",
    "addressLine": "Avenida Doutor Abelardo Velloso, 522, Centro",
    "scheduleLine": "",
    "instagramUrl": "",
    "whatsappUrl": "https://wa.me/5575988598303",
    "email": "gilsonantonio@gmail.com",
    "phone": "(75) 98859-8303",
    "displayOrder": 26,
    "isActive": true,
    "latitude": -13.0301649,
    "longitude": -39.5937849,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Pousada%20Girassol,%20Avenida%20Doutor%20Abelardo%20Velloso,%20522,%20Centro,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "lodging"
  },
  {
    "publicId": "card-hotel-bosque",
    "pointId": "hotel-bosque",
    "category": "hotel",
    "name": "Pousada do Bosque",
    "subtitle": "Reserva por e-mail e telefone",
    "description": "Pousada com canal de reservas por e-mail, presente na relação local de hospedagens",
    "imageUrl": "public/images/pousadas/bosque.webp",
    "imageAlt": "Pousada do Bosque",
    "addressLine": "Praça da Bandeira, 269, Centro",
    "scheduleLine": "",
    "instagramUrl": "https://www.instagram.com/pousadadobosqueamargosa/",
    "whatsappUrl": "",
    "email": "reservas@pousadadobosqueamargosa.com.br",
    "phone": "+557536342663",
    "displayOrder": 27,
    "isActive": true,
    "latitude": -13.0315483,
    "longitude": -39.6000694,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Pousada%20do%20Bosque,%20Praca%20da%20Bandeira,%20269,%20Centro,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "lodging"
  },
  {
    "publicId": "card-hotel-dona-marieta",
    "pointId": "hotel-dona-marieta",
    "category": "hotel",
    "name": "Pousada Dona Marieta",
    "subtitle": "Múltiplos contatos para reserva",
    "description": "Hospedagem com mais de um telefone de contato para informações e reserva",
    "imageUrl": "public/images/hero-amargosa.jpeg",
    "imageAlt": "Pousada Dona Marieta",
    "addressLine": "",
    "scheduleLine": "",
    "instagramUrl": "",
    "whatsappUrl": "https://wa.me/5575983710724",
    "email": "(75) 98371-0724 / (75) 98352-6794 / (75) 98896-4894",
    "phone": "",
    "displayOrder": 28,
    "isActive": true,
    "latitude": -13.0231323,
    "longitude": -39.6028382,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Pousada%20Dona%20Marieta,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "lodging"
  },
  {
    "publicId": "card-hotel-imperial",
    "pointId": "hotel-imperial",
    "category": "hotel",
    "name": "Hotel Imperial",
    "subtitle": "Hospedagem com contato por e-mail",
    "description": "Opção de hospedagem com atendimento por e-mail e telefone fixo em Amargosa",
    "imageUrl": "public/images/pousadas/imperial.webp",
    "imageAlt": "Hotel Imperial",
    "addressLine": "Rua Aldemiro Vaz Sampaio, 100, Centro",
    "scheduleLine": "",
    "instagramUrl": "https://www.instagram.com/imperialhotelamargosa/",
    "whatsappUrl": "",
    "email": "Imperialhotel.2023@gmail.com",
    "phone": "+557536341925",
    "displayOrder": 29,
    "isActive": true,
    "latitude": -13.0285661,
    "longitude": -39.6043237,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Pousada%20Imperial,%20Rua%20Aldemiro%20Vaz%20Sampaio,%20100,%20Centro,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "lodging"
  },
  {
    "publicId": "card-hotel-sampaio",
    "pointId": "hotel-sampaio",
    "category": "hotel",
    "name": "Pousada Sampaio",
    "subtitle": "Contato com Denise",
    "description": "Hospedagem com contato direto pelo telefone informado no cadastro local",
    "imageUrl": "public/images/pousadas/sampaio.webp",
    "imageAlt": "Pousada Sampaio",
    "addressLine": "Rua Moreira Coelho, 28, Centro",
    "scheduleLine": "",
    "instagramUrl": "",
    "whatsappUrl": "https://wa.me/5571988555456",
    "email": "Contato Denise",
    "phone": "(71) 98855-5456",
    "displayOrder": 30,
    "isActive": true,
    "latitude": -13.03061,
    "longitude": -39.6013196,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Pousada%20Sampaio,%20Rua%20Moreira%20Coelho,%2028,%20Centro,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "lodging"
  },
  {
    "publicId": "card-hotel-baitinga",
    "pointId": "hotel-baitinga",
    "category": "hotel",
    "name": "Resort Baitinga",
    "subtitle": "Hospedagem sob consulta",
    "description": "Opção de hospedagem listada no material local, com atendimento por WhatsApp e perfil voltado a estadias na zona rural",
    "imageUrl": "public/images/pousadas/baitinga.webp",
    "imageAlt": "Resort Baitinga",
    "addressLine": "Povoado Baitinga, 15 - Rural, Amargosa - BA, 45300-000",
    "scheduleLine": "",
    "instagramUrl": "https://www.instagram.com/baitingaclubeepousada/",
    "whatsappUrl": "https://wa.me/5575992234496",
    "email": "",
    "phone": "(75) 99223-4496",
    "displayOrder": 31,
    "isActive": true,
    "latitude": -13.0156032,
    "longitude": -39.5754319,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Resort%20Baitinga,%20Povoado%20Baitinga,%2015%20-%20Rural,%20Amargosa%20-%20BA,%2045300-000,%20Brasil",
    "markerIcon": "lodging"
  },
  {
    "publicId": "card-hotel-asa-branca",
    "pointId": "hotel-asa-branca",
    "category": "hotel",
    "name": "Motel Asa Branca",
    "subtitle": "Contato por telefone",
    "description": "Estabelecimento de hospedagem listado entre as opções existentes no município",
    "imageUrl": "public/images/praca-iraci-silva-praca-do-cristo.jpg",
    "imageAlt": "Motel Asa Branca",
    "addressLine": "BA-540, 400, Rodovia Amargosa-Mutuipe",
    "scheduleLine": "",
    "instagramUrl": "",
    "whatsappUrl": "",
    "email": "",
    "phone": "(75) 6334-1325",
    "displayOrder": 32,
    "isActive": true,
    "latitude": -13.0130724,
    "longitude": -39.6114608,
    "directionsUrl": "https://www.google.com/maps/dir/?api=1&destination=Motel%20Asa%20Branca,%20BA-540,%20400,%20Rodovia%20Amargosa-Mutuipe,%20Amargosa,%20Bahia,%20Brasil",
    "markerIcon": "lodging"
  }
];
